project:
  type: website

website:
  title: "Casey Wood"
  navbar:
    background: primary
    search: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/C-Wood
format:
  html:
    theme: cosmo
    css: styles.css



